function [fitresult, gof] = createFit1(x, meanProfile, c_left, c_right)
%CREATEFIT1(X,MEANPROFILE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x
%      Y Output: meanProfile
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Mar-2024 18:08:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, meanProfile );
fit_str = sprintf( '%.3f+(%.3f-%.3f)/(1+exp((x1-x)/lambda1))',c_left,c_right,c_left);
% Set up fittype and options.
ft = fittype( fit_str, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.1 0.1 10 25];
opts.StartPoint = [0.5 28];
opts.Upper = [4 4 15 30];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Sigmoid' );
h = plot( fitresult, xData, yData );
legend( h, 'meanProfile vs. x', 'Sigmoid', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'meanProfile', 'Interpreter', 'none' );
grid on


